apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-onfailure
spec:
  restartPolicy: OnFailure
  containers:
  - name: nginx-container
    image: nginx:latest
    command: ['sh', '-c', 'echo Ejemplo de pod fallado && exit 1']
