apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod-never
spec:
  restartPolicy: Never
  containers:
  - name: busybox-container
    image: busybox
    command: ['sh', '-c', 'echo Ejemplo de pod fallado && exit 1']